---
spring.profiles: docker
server.port: 80
spring:
  application.name: event-service
  cloud:
    function.definition: eventHandler
    stream:
      bindings:
        eventHandler-in-0.destination: ${app.events.topic}
        eventHandler-in-0.group: eventGroup
      default-binder: kafka
      kafka:
        binder:
          replicationFactor: 1
