---
spring.profiles: docker

server.port: 80

server.error.include-message: always

spring:
  application.name: product-composite
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
app:
  auth-server: auth-server
  clients:
    TIKI: tiki/api/v1/products
    LAZADA: lazada/api/v1/products
    SHOPEE: shopee/api/v1/products

spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://${app.auth-server}/.well-known/jwks.json

#logging:
#  level:
#    root: INFO
#    org.springframework.web.server.adapter.HttpWebHandlerAdapter: WARN

